name: wander_lanka
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # --- Core / UI ---
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  http: ^1.4.0

  # --- Firebase ---
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6

  # --- Auth widgets ---
  google_sign_in: ^6.2.1
  # flutter_facebook_auth: ^5.0.0   # Uncomment if adding Facebook login

  # --- Forms / Localisation ---
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.21

  # --- Maps & Location (Free & Offline-ready) ---
  google_maps_flutter: ^2.5.2
  geolocator: ^14.0.0
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_polyline_points: ^2.0.0
  image_picker: ^1.1.2

  # --- State Management & Storage ---
  shared_preferences: ^2.2.2
  provider: ^6.1.2

  # New
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  # Uncomment and add images if needed
  # - images/a_dot_burr.jpeg
  # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700



