name: wander_lanka
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # --- Core / UI ---
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.1.2

  # --- Firebase ---
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6

  # --- Authentication ---
  google_sign_in: ^6.2.1
  # flutter_facebook_auth: ^5.0.0  # Uncomment if needed

  # --- Forms / Localization ---
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.21
  flutter_localizations:
    sdk: flutter

  # --- Maps & Location ---
  google_maps_flutter: ^2.5.2
  geolocator: ^14.0.0
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_polyline_points: ^2.0.0

  # --- State Management & Storage ---
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  # --- Utilities ---
  http: ^1.4.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf






